@startuml
title: IRS-DV app
skinparam actorStyle awesome
actor consumer as user


component "IRS-DV app FRONTEND" as irsdv <<Sytem>> {

component App as mainPage {

node "Fill search parameters" as parameters 
node "Select Environment" as env
node "Request information/submit form" as button
node "Visualization and information" as visual
node "Job store" as store

} 
}


component "Shared services" {
component "KeyCloak" as keycloak
boundary "token" as token
component "IRS" as irs
component "API" as api
}



user .> env
env .> keycloak
keycloak <..> token
keycloak <..> irs
keycloak .> parameters

irs <..> api

parameters ..> button
button ..> api
api .> store

store ..> visual

@enduml